name: Publish
permissions:
  contents: read
  packages: write
  id-token: write # Required for OIDC

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  publish-npm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm version ${TAG_NAME} --git-tag-version=false
        env:
          TAG_NAME: ${{ github.event.release.tag_name || github.event.inputs.version }}
      - run: npm --ignore-scripts publish
